### PR TITLE
add typescript support

### PR DESCRIPTION
**Pull request by cnjack**

### CODE REVIEW

**Comment by sgotre** [comment]
@emn178 any plans to merge? thank you for this package!

**Comment by ChocolateLoverRaj** [comment]
@cnjack If @emn178  doesn't merge this PR, you could just make a PR in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by cnjack** [comment]
> @cnjack If @emn178 doesn't merge this PR, you could just make a PR in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

ok, i will do it

**Comment by zacharytyhacz** [comment]
> > @cnjack If @emn178 doesn't merge this PR, you could just make a PR in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).
> 
> ok, i will do it

🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏

**Comment by emn178** [comment]
added in v0.7.0

**Pull request closed without merging**
